[tool.poetry]
name = "tic-tac-toe"
version = "0.1.0"
description = ""
authors = ["JAKEDENG1 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
player = "^0.6.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
